updated pwd.yml

diff --git a/pwd.yml b/pwd.yml
--- a/pwd.yml
+++ b/pwd.yml
@@ -1,157 +1,99 @@
 version: "3"
 
 services:
-  traefik:
-    image: "traefik:v2.2"
-    ports:
-      - "80:80"
-    deploy:
-      restart_policy:
-        condition: on-failure
-      labels:
-        - "traefik.enable=true"
-    command:
-      - "--providers.docker"
-      - "--providers.docker.exposedbydefault=false"
-      - "--entrypoints.web.address=:80"
-      - "--providers.docker.swarmmode"
-      - "--accesslog"
-      - "--log"
-    volumes:
-      - /var/run/docker.sock:/var/run/docker.sock:ro
-
-  erpnext-nginx:
-    image: frappe/erpnext-nginx:edge
-    environment:
-      - FRAPPE_PY=erpnext-python
-      - FRAPPE_PY_PORT=8000
-      - FRAPPE_SOCKETIO=frappe-socketio
-      - SOCKETIO_PORT=9000
-    deploy:
-      restart_policy:
-        condition: on-failure
-      labels:
-        - "traefik.enable=true"
-        - "traefik.http.routers.erpnext-nginx.rule=HostRegexp(`{catchall:.*}`)"
-        - "traefik.http.middlewares.erpnext-nginx.headers.customrequestheaders.Host=erpnext-nginx"
-        - "traefik.http.routers.erpnext-nginx.middlewares=erpnext-nginx"
-        - "traefik.http.routers.erpnext-nginx.entrypoints=web"
-        - "traefik.http.services.erpnext-nginx.loadbalancer.server.port=8080"
-    volumes:
-      - sites-vol:/var/www/html/sites:rw
-      - assets-vol:/assets:rw
-
-  erpnext-python:
-    image: frappe/erpnext-worker:edge
-    deploy:
-      restart_policy:
-        condition: on-failure
-    environment:
-      - MARIADB_HOST=mariadb
-      - REDIS_CACHE=redis-cache:6379
-      - REDIS_QUEUE=redis-queue:6379
-      - REDIS_SOCKETIO=redis-socketio:6379
-      - SOCKETIO_PORT=9000
-      - AUTO_MIGRATE=1
-    volumes:
-      - sites-vol:/home/frappe/frappe-bench/sites:rw
-      - assets-vol:/home/frappe/frappe-bench/sites/assets:rw
-
-  frappe-socketio:
-    image: frappe/frappe-socketio:edge
+  backend:
+    # image: frappe/erpnext:v14
+    image: usman89/myrepo:6.0.0
     deploy:
       restart_policy:
         condition: on-failure
     volumes:
-      - sites-vol:/home/frappe/frappe-bench/sites:rw
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
 
-  erpnext-worker-default:
-    image: frappe/erpnext-worker:edge
-    deploy:
-      restart_policy:
-        condition: on-failure
-    command: worker
-    depends_on:
-      - redis-queue
-      - redis-cache
-    volumes:
-      - sites-vol:/home/frappe/frappe-bench/sites:rw
-
-  erpnext-worker-short:
-    image: frappe/erpnext-worker:edge
-    deploy:
-      restart_policy:
-        condition: on-failure
-    command: worker
-    environment:
-      - WORKER_TYPE=short
-    depends_on:
-      - redis-queue
-      - redis-cache
-    volumes:
-      - sites-vol:/home/frappe/frappe-bench/sites:rw
-
-  erpnext-worker-long:
-    image: frappe/erpnext-worker:edge
-    deploy:
-      restart_policy:
-        condition: on-failure
-    command: worker
-    environment:
-      - WORKER_TYPE=long
-    depends_on:
-      - redis-queue
-      - redis-cache
-    volumes:
-      - sites-vol:/home/frappe/frappe-bench/sites:rw
-
-  erpnext-schedule:
-    image: frappe/erpnext-worker:edge
-    deploy:
-      restart_policy:
-        condition: on-failure
-    command: schedule
-    depends_on:
-      - redis-queue
-      - redis-cache
-    volumes:
-      - sites-vol:/home/frappe/frappe-bench/sites:rw
-
-  redis-cache:
-    image: redis:latest
-    deploy:
-      restart_policy:
-        condition: on-failure
-    volumes:
-      - redis-cache-vol:/data
-
-  redis-queue:
-    image: redis:latest
-    deploy:
-      restart_policy:
-        condition: on-failure
-    volumes:
-      - redis-queue-vol:/data
-
-  redis-socketio:
-    image: redis:latest
-    deploy:
-      restart_policy:
-        condition: on-failure
-    volumes:
-      - redis-socketio-vol:/data
-
-  site-configurator:
-    image: frappe/erpnext-worker:edge
+  configurator:
+    image: frappe/erpnext:v14
     deploy:
       restart_policy:
         condition: none
-    command: ["bash", "-c", "echo erpnext-nginx > /sites/currentsite.txt"]
+    entrypoint:
+      - bash
+      - -c
+    # add redis_socketio for backward compatibility
+    command:
+      - >
+        ls -1 apps > sites/apps.txt;
+        bench set-config -g db_host $$DB_HOST;
+        bench set-config -gp db_port $$DB_PORT;
+        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
+        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
+        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
+        bench set-config -gp socketio_port $$SOCKETIO_PORT;
+    environment:
+      DB_HOST: db
+      DB_PORT: "3306"
+      REDIS_CACHE: redis-cache:6379
+      REDIS_QUEUE: redis-queue:6379
+      SOCKETIO_PORT: "9000"
     volumes:
-      - sites-vol:/sites:rw
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
 
-  mariadb:
+  create-site:
+    image: frappe/erpnext:v14
+    deploy:
+      restart_policy:
+        condition: none
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+    entrypoint:
+      - bash
+      - -c
+    environment:
+      DB_HOST: db
+      DB_PORT: "3306"
+      REDIS_CACHE: redis-cache:6379
+      REDIS_QUEUE: redis-queue:6379
+      MYSQL_ROOT_PASSWORD: 123
+      SOCKETIO_PORT: "9000"
+    command:
+      - >
+        wait-for-it -t 120 db:3306;
+        wait-for-it -t 120 redis-cache:6379;
+        wait-for-it -t 120 redis-queue:6379;
+        export start=`date +%s`;
+        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+        do
+          echo "Waiting for sites/common_site_config.json to be created";
+          sleep 5
+          if (( `date +%s`-start > 120 )); then
+            echo "could not find sites/common_site_config.json with required keys";
+            exit 1
+          fi
+        done;
+        echo "sites/common_site_config.json found";
+        bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=123 --install-app erpnext --set-default frontend;
+        # bash -c '
+        #   if [[ -d /home/frappe/frappe-bench/apps/associated_terminals ]]; then
+        #     echo "The '\''associated_terminals'\'' app already exists. Exiting.";
+        #     exit 0;
+        #   else
+        #     echo "The '\''associated_terminals'\'' app does not exist. Fetching...";
+        #     bench get-app https://x-token-auth:ATCTT3xFfGN01ZGPAktgG5e_SQ02ryC4NimdhgBHl57h0aQ0xsEdNyfyOytjlnCok-ErgKPeyRh24Kw31KtDNKVYxTMeaKNQj0sZL2ze8FGCJgNkbqCzXq_-lMU248UkkdGbOWo-4pVSSIYUDI1WnmpR5UYvO_GqwWys-8QmJcBGxm1M-6lKBnY=39B560F8@bitbucket.org/persona-lworkspace/associated-terminals.git;
+        #     echo "Installing '\''associated_terminals'\'' app...";
+        #     bench --site frontend install-app associated_terminals;
+        #   fi;
+        # ';
+
+  db:
     image: mariadb:10.6
+    healthcheck:
+      test: mysqladmin ping -h localhost --password=123
+      interval: 1s
+      retries: 15
     deploy:
       restart_policy:
         condition: on-failure
@@ -161,34 +103,107 @@ services:
       - --skip-character-set-client-handshake
       - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
     environment:
-      - MYSQL_ROOT_PASSWORD=admin
-      # Sometimes db initialization takes longer than 10 seconds and site-creator goes away.
-      # Frappe doesn't use CONVERT_TZ() function that requires time zone info, so we can just skip it.
-      - MYSQL_INITDB_SKIP_TZINFO=1
+      MYSQL_ROOT_PASSWORD: 123
     volumes:
-      - mariadb-conf-vol:/etc/mysql/conf.d
-      - mariadb-vol:/var/lib/mysql
+      - db-data:/var/lib/mysql
 
-  site-creator:
-    image: frappe/erpnext-worker:edge
+  frontend:
+    image: usman89/myrepo:6.0.0
+    # image: frappe/erpnext:v14
     deploy:
       restart_policy:
-        condition: none
-    command: new
+        condition: on-failure
+    command:
+      - nginx-entrypoint.sh
     environment:
-      - SITE_NAME=erpnext-nginx
-      - DB_ROOT_USER=root
-      - MYSQL_ROOT_PASSWORD=admin
-      - ADMIN_PASSWORD=admin
-      - INSTALL_APPS=erpnext
+      BACKEND: backend:8000
+      FRAPPE_SITE_NAME_HEADER: frontend
+      SOCKETIO: websocket:9000
+      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
+      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
+      UPSTREAM_REAL_IP_RECURSIVE: "off"
+      PROXY_READ_TIMEOUT: 120
+      CLIENT_MAX_BODY_SIZE: 50m
     volumes:
-      - sites-vol:/home/frappe/frappe-bench/sites:rw
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+    ports:
+      - "8080:8080"
+
+  queue-long:
+    #image: frappe/erpnext:v14
+    image: usman89/myrepo:6.0.0
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - bench
+      - worker
+      - --queue
+      - long,default,short
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+
+  queue-short:
+    #image: frappe/erpnext:v14
+    image: usman89/myrepo:6.0.0
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - bench
+      - worker
+      - --queue
+      - short,default
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+
+  redis-queue:
+    image: redis:6.2-alpine
+    deploy:
+      restart_policy:
+        condition: on-failure
+    volumes:
+      - redis-queue-data:/data
+
+  redis-cache:
+    image: redis:6.2-alpine
+    deploy:
+      restart_policy:
+        condition: on-failure
+    volumes:
+      - redis-cache-data:/data
+
+  scheduler:
+    image: frappe/erpnext:v14
+    #image: usman89/myrepo:6.0.0
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - bench
+      - schedule
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+
+  websocket:
+    image: frappe/erpnext:v14
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - node
+      - /home/frappe/frappe-bench/apps/frappe/socketio.js
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
 
 volumes:
-  mariadb-vol:
-  mariadb-conf-vol:
-  redis-cache-vol:
-  redis-queue-vol:
-  redis-socketio-vol:
-  assets-vol:
-  sites-vol:
+  db-data:
+  redis-queue-data:
+  redis-cache-data:
+  sites:
+  logs:
